export const TASK_GANTT_PROJECT_MANAGEMENT = 'TASK_GANTT_PROJECT_MANAGEMENT';
export const TASK_GANTT_RESOURCE_MANAGEMENT = 'TASK_GANTT_RESOURCE_MANAGEMENT';
export const TASK_DATA_SET_VISUALISATION = 'TASK_DATA_SET_VISUALISATION';
export const TASK_LINE_TIME_SERIES = 'TASK_LINE_TIME_SERIES';
export const TASK_IRREGULAR_TIME_SERIES = 'TASK_IRREGULAR_TIME_SERIES';

export const TASKS = [
    TASK_GANTT_PROJECT_MANAGEMENT,
    TASK_DATA_SET_VISUALISATION,
    TASK_IRREGULAR_TIME_SERIES,
    TASK_GANTT_RESOURCE_MANAGEMENT,
    TASK_LINE_TIME_SERIES
];